Bookstore: connect to API
mrparkersson/React-Bookstore pull request #3
Opened 2022-02-23 13:43 UTC by mrparkersson

Pull request
Amo Parker Prince

What does this PR do?

Designing React bookstore template in the component directory

Description of the task to be completed
A tests using Jest and React test library

Used React in writing JSX and adding Redux store to handle states in the Components
Called and remove only when API data is successful 

created test.MD files that have been ignored
How should it be tested
By running npm test in the terminal.

clone the repository
git clone https://github.com/mrparkersson/React-Bookstore
navigate to the folder
cd bookstore
checkout the feature

2022-02-23 14:15 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @mrparkersson,

Good job so far!
✔️ Good documentation
✔️ Linters are passing
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-23 14:15 UTC, TedLivist commented on src/redux/removebook.js
> +
- [ ] It is not good practice to commit and push console logs as they expose confidential data. It also kills performance. Kindly remove them.

2022-02-23 14:15 UTC, TedLivist commented on src/components/BookList.js
>  const BookList = () => {
- [ ] You books should be persisted in the server such that when the page is refreshed the books should be fetched from the API presented on the page. But that is not the case in your app. After adding books and refreshing the books disappear from the app. Kindly ensure that your books are fetched and presented when the browser is refreshed.

  Initially | Books are added | Page is refreshed 
  :---:|:---:|:---:
  ![parker-1](https://user-images.githubusercontent.com/36542986/155335086-9c352b77-ee26-47e8-ba7b-9fe82fdec2d7.jpg) | ![parker-3](https://user-images.githubusercontent.com/36542986/155335091-71f798f2-25f7-41a7-8969-ddb579ad65fe.jpg) | ![parker-4](https://user-images.githubusercontent.com/36542986/155335096-8b9666d4-5d87-439b-be64-deae25920b25.jpg)

- [ ] **[OPTIONAL]** It would be nice to make this component your default (root) route like in the image below so that users are not presented with an empty page when your app is run initially. Remember to configure the Nav component **Link** to match this too.

  ![parker-route](https://user-images.githubusercontent.com/36542986/155336135-a4a1952a-1e4c-4640-84e5-bdaa66e7e223.jpg)

2022-02-24 06:44 UTC, FrederickMih approved these changes
### Hi @mrparkersson , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-24 07:02 UTC, merged